### PR TITLE
update JSON adapter pagination links how to guide

### PR DESCRIPTION
**Pull request by edwinlunando**

### CODE REVIEW

**Comment by bf4** [comment]
hi @edwinlunando thanks for this.  Can you explain your motivation for the new example and for removing the existing example? What version of AMS are you targeting?

**Comment by edwinlunando** [comment]
Because the current master documentation on adding pagination link is now broken. I tried the master version and following the guide, but it is not working. https://github.com/rails-api/active_model_serializers/issues/1466

**Comment by bf4** [comment]
@edwinlunando would you be up to amending this PR to include a failing test for the documented scenario? That should be working.

**Comment by bf4** [comment]
Looks like the meta option was moved into the adapter in https://github.com/rails-api/active_model_serializers/pull/1233/files#diff-1bab1447950ba5f1422e5a9c8442c687L10

**Comment by edwinlunando** [comment]
Yes. That's why the old method on adding pagination links is not working. The current docs is misleading.

**Comment by ScottKbka** [comment]
:+1: to this or something similar. I was just stumped on the same issue.

**Comment by edwinlunando** [comment]
Any feedback on this? I believe this is quite important since the current docs is wrong.

**Comment by bf4** [comment]
Sorry for delay and thanks for following up!  :heart: I'll review soon

B mobile phone

**Pull request merged**
