### PR TITLE
Add support for Rails 6.0.0 on Travis

### PR DESCRIPTION
**Pull request by wasifhossain**
https://weblog.rubyonrails.org/2019/7/30/Rails-6-0-rc2-released/

### CODE REVIEW

**Comment by bf4** [comment]
Did you look at the failures?

**Comment by wasifhossain** [comment]
yes. 

in first run, it stuck at Ruby 2.1.10 + Rails 4.2, which turned into success after rebuilding.
the 2nd one is related to JDK, which I think is unrelated to the PR

**Comment by wasifhossain** [comment]
JDK related issue: https://travis-ci.community/t/error-installing-oraclejdk8-expected-feature-release-number-in-range-of-9-to-14-but-got-8/3766

**Comment by wasifhossain** [comment]
updates:

I have changed `oraclejdk8` to `openjdk8` following [this commit](https://github.com/jruby/jruby/commit/fa66606a85ce65bba6f7e7a70117782ee4b36711) from jruby community and this worked straightaway :tada: 

besides, I took the chance to bump the jruby 9.1.x version to the latest (**9.1.17.0**) along with including **jruby 9.2.x** (**9.2.7.0**) and **master**.

9.1.x is expected to cover all the rails versions (4.1 to master), while 9.2.x+ from rails 4.2 to master.

btw, I moved all the **jruby tests** under **allowed failures** temporarily to see how they go on travis.

**Comment by wasifhossain** [comment]
looks like **rails 5.2+** failed across all jruby versions. let me work on it.

**Comment by wasifhossain** [comment]
now **jruby 9.2.x/master** gets stuck at **rails master**, which I think is fine for now. 

going to keep these 2 cases under **allowed failures** section, while moving back all other jruby tests to the **required** section.

**Comment by wasifhossain** [comment]
image
these tests have little chance to pass as we go forward. so i think we may drop support for these tests from travis.

**Comment by wasifhossain** [comment]
@bf4 tests look good now. would you take another look and let me know if any changes are left for this PR. otherwise you may give it a go :raised_hands: thanks

**Comment by gchapim** [comment]
@wasifhossain Rails 6.0.0 was released. Do you want me to create another PR based on yours to include Rails 6.0.0 on travis as well?

**Pull request merged**
