### PR TITLE
Update outside_controller_use.md

### PR DESCRIPTION
**Pull request by AlexVPopov**
#### Purpose
Better documentation about serializing resources outside of controllers.

#### Related GitHub issues
#1975

### CODE REVIEW

**Comment by AlexVPopov** [comment]
I appreciate feedback for this PR, as it is kind of small :)

**Comment by Tonkpils** [comment]
Looks good! Thought I'm not great at grammar I don't think the comma is needed or there should be a comma 

> `ActiveModelSerializers::SerializableResource.new`, can be a

**Comment by AlexVPopov** [comment]
@Tonkpils PR updated.

**Comment by groyoh** [comment]
@AlexVPopov I don't know if you don't know it or didn't think about it but since you only changed the docs, you could have added `[skip ci]` to your commit :wink:

**Comment by AlexVPopov** [comment]
@groyoh PR updated. Also, I didn't know about the `[skip ci]` trick, nice :wink: Also, I find the `mention-bot`, which pings people, based on the history of a file ingenious.

**Pull request merged**
