### PR TITLE
pass context to ArraySerializer

### PR DESCRIPTION
**Pull request by lanej**

### CODE REVIEW

**Comment by kurko** [comment]
Do you mind adding a test, a mention in the documentation and a little bit of context on why you want this merged? Why `context` and not something more general, that other people could use? Perhaps `options` would be a better fit, which you could then use `context` in your app (via hash)?

**Comment by lanej** [comment]
will do

**Comment by lanej** [comment]
@kurko context is available for singular serializers.  My issue was that context is not "distributed" to the singular serializers when going through an array serializer.

In my opinion, this more of a bug fix to make the collection / singular context availability consistent.

**Comment by kurko** [comment]
Thanks for the explanation. I'm not using 0.9 for years now, so I needed some `context` :grin:

**Comment by lanej** [comment]
:rimshot:

**Pull request merged**
