### PR TITLE
Remove SerializableResource.serialize in favor of `.new`

### PR DESCRIPTION
**Pull request by bf4**
Per discussion in https://github.com/rails-api/active_model_serializers/issues/1098

### CODE REVIEW

**Comment by bf4** [comment]
Failures on appveyour are race conditions we haven't fixed yet

- https://ci.appveyor.com/project/joaomdmoura/active-model-serializers/build/49/job/pf3g0vp1otqecv42
- https://ci.appveyor.com/project/joaomdmoura/active-model-serializers/build/49/job/j0tijlxbeluf9r5e

```plain
 1) Failure:
ActionController::Serialization::ImplicitSerializerTest#test_cache_expiration_on_update [C:/projects/active-model-serializers/test/action_controller/serialization_test.rb:394]:
--- expected
+++ actual
@@ -1 +1 @@
-"{\"id\":1,\"title\":\"ZOMG a New Post\",\"body\":\"Body\",\"comments\":[{\"id\":1,\"body\":\"ZOMG A COMMENT\"}],\"blog\":{\"id\":999,\"name\":\"Custom blog\"},\"author\":{\"id\":1,\"name\":\"Joao Moura.\"}}"
+"{\"id\":1,\"title\":\"New Post\",\"body\":\"Body\",\"comments\":[{\"id\":1,\"body\":\"ZOMG A COMMENT\"}],\"blog\":{\"id\":999,\"name\":\"Custom blog\"},\"author\":{\"id\":1,\"name\":\"Joao Moura.\"}}"
 ```

**Comment by NullVoxPopuli** [comment]
:+1:

**Comment by beauby** [comment]
Should we put a deprecation warning until 0.10 is released, rather than suppressing the method?

**Comment by joaomdmoura** [comment]
I don't think we needed the warning because it was not even on the RC2, but I'm not against it if you think we should.
But I think we should update/add some docs about it on our new `docs` for sure.

**Comment by beauby** [comment]
Oh, right. Let's just remove it then.

**Comment by NullVoxPopuli** [comment]
@beauby are you finished with this?

**Pull request merged**
