### PR TITLE
Install bundler ~> 1.17 on Travis

### PR DESCRIPTION
**Pull request by krzysiek1507**

### CODE REVIEW

**Comment by bf4** [comment]
related https://github.com/rails-api/active_model_serializers/pull/2181

let's remove the bundler restriction in the Gemfile, and I think that should fix it?

**Comment by krzysiek1507** [comment]
Now should be fixed.
Bundler 2 drops Ruby < 2.3.
Rails 4.1 requires Bundler < 2.

`BUNDLER_VERSION=1.17.3` enforces bundler 1.17.3.

**Comment by bf4** [comment]
@krzysiek1507 take a look at https://github.com/rails/rails/pull/34851/files

```diff
before_install:
  - "rm ${BUNDLE_GEMFILE}.lock"
  - "travis_retry gem update --system || travis_retry gem update --system 2.7.8"
-  - "travis_retry gem install bundler"
+  - "travis_retry gem install bundler || travis_retry gem install bundler -v 1.17.3"
```

and https://github.com/rails/rails/pull/34925/files

```yaml
  - "rm ${BUNDLE_GEMFILE}.lock"
  - "travis_retry gem update --system 2.6.13"
  - "travis_retry gem install bundler -v '<2'"
```

and the gemspec 

```
  s.add_dependency 'bundler',         '>= 1.3.0', '< 2.0'
```

so maybe we could change our gemspec development dep like that

**Comment by krzysiek1507** [comment]
@bf4 my solution works except Ruby 2.4.2 and rails master because rails master requires ruby 2.5 so I've excluded it.

**Pull request merged**
