### PR TITLE
Serializers now inherit attributes

### PR DESCRIPTION
**Pull request by groyoh**
I changed the behaviour of the serializer so that subclasses of a serializer also inherit the associations and attributes of its parent.

### CODE REVIEW

**Comment by joaomdmoura** [comment]
LGTM @groyoh thank you so much, nice work, any thoughts about it @kurko ?

**Comment by benedikt** [comment]
I'd love to see this merged! Is there anything that has to be done before it's ready for a merge?

**Comment by remear** [comment]
I tested these changes locally and they worked great. I'd also like to see this be merged soon.

**Comment by joaomdmoura** [comment]
Tks for the feedback @benedikt and @remear I'll try to push it forward as soon as possible :smile:

**Comment by joaomdmoura** [comment]
Just check it! I'm merging it :+1:

**Pull request merged**
