### PR TITLE
Deserializers

### PR DESCRIPTION
**Pull request by beauby**
Following @joaomdmoura 's work and the discussion on #950, here is an up-to-date version of the deserializers, with some tests. Still a WIP.

### CODE REVIEW

**Comment by beauby** [comment]
Added whitelisting at runtime, so that people can restrict the attributes/relationships allowed as follows:
```ruby
def create_params
  UserSerializer.deserialize(params, [:username, :email, :password, :referer])
end

def update_params
  PostSerializer.deserialize(params, [:username])
end

def create
  @post = Post.create(create_params)
  # ...
end

def update
  @post = Post.find_by(...)
  @post.update_attributes(update_params)
  # ...
end
```

**Comment by beauby** [comment]
Finally added a test of end-to-end deserialization (backed by ActiveRecord).

**Comment by beauby** [comment]
For some reason the installation of `sqlite3` fails on the jruby test envs.

**Comment by joaomdmoura** [comment]
@beauby Could you submit this to my deserialization branch specifically? Otherwise I won;t be able to merge it.

**Pull request closed without merging**
