### PR TITLE
[0.9] Benchmarks

### PR DESCRIPTION
**Pull request by yosiat**
Hi,

Here is initial benchmarks for AMS 0.9 version.
I have copied the benchmarking infrastructure and created some benchmarks to get some initial results to act upon.

Current status:
version: 0.9.6, rails version: 4.2.8, ruby: 2.3.3p222

| Serializer  | ip/s | objects allocated |
| ------------- | ------------- |------------- |
|Single: DefaultSerializer | 26898.121 | 76|
|ArraySerializer | 4341.036 | 346|
|ArraySerializer: each_serializer: DefaultSerializer | 17288.409 | 122|
|FlatAuthorSerializer | 26483.242 | 85|
|ArraySerializer: each_serializer: FlatAuthorSerializer | 19398.298 | 114|
|AuthorWithDefaultRelationshipsSerializer | 86.694 | 18634|
|ArraySerializer: each_serializer: AuthorWithDefaultRelationshipsSerializer | 80.462 | 20091|

After some investigating it looks like that most of the time we spend in `serializer_for`,
I thought about doing the same logic done in `0.10` with serializers cache.

What do you think?

### CODE REVIEW

**Comment by bf4** [comment]
@yosiat Looks good to me

**Comment by yosiat** [comment]
@bf4 what do you think about the serializer cache?

I made a change and ran the benchmark and it looks much better:

| Serializer  | ip/s | objects allocated |
| ------------- | ------------- |------------- |
|Single: DefaultSerializer | 24870.15 | 76|
|ArraySerializer | 13612.293 | 131|
|ArraySerializer: each_serializer: DefaultSerializer | 16368.404 | 122|
|FlatAuthorSerializer | 25662.635 | 85|
|ArraySerializer: each_serializer: FlatAuthorSerializer | 19157.602 | 114|
|AuthorWithDefaultRelationshipsSerializer | 325.933 | 6241|
|ArraySerializer: each_serializer: AuthorWithDefaultRelationshipsSerializer | 331.454 | 6270|
|AuthorWithSpecifiedDefaultRelationshipsSerializer | 387.585 | 5783|
|ArraySerializer: each_serializer: AuthorWithSpecifiedDefaultRelationshipsSerializer | 388.285 | 5812|
|AuthorWithArrayRelationshipsSerializer | 387.524 | 5795|
|ArraySerializer: each_serializer: AuthorWithArrayRelationshipsSerializer | 383.575 | 5824|

If you like this I will submit PR after this one get's merged.

**Comment by yosiat** [comment]
What do you think about the serializer cache idea? 

Some initial benchmarks show real improvement in here:

| Serializer  | ip/s | objects allocated |
| ------------- | ------------- |------------- |
|Single: DefaultSerializer | 27043.366 | 76|
|ArraySerializer | 14775.977 | 134|
|ArraySerializer: each_serializer: DefaultSerializer | 17252.294 | 125|
|FlatAuthorSerializer | 26830.435 | 85|
|ArraySerializer: each_serializer: FlatAuthorSerializer | 19013.011 | 117|
|AuthorWithDefaultRelationshipsSerializer | 374.519 | 5852|
|ArraySerializer: each_serializer: AuthorWithDefaultRelationshipsSerializer | 375.409 | 5884|

**Comment by bf4** [comment]
@yosiat sounds good.

**Comment by yosiat** [comment]
@bf4 great! once this pull request is merged I will create another for the cache.

**Comment by bf4** [comment]
@yosiat did you look at why the tests are failing? does our ci need to be updated?

**Comment by yosiat** [comment]
@bf4 the error is because nokogiri:
```
Gem::InstallError: nokogiri requires Ruby version >= 2.1.0.
Installing sqlite3 1.3.13
An error occurred while installing nokogiri (1.7.0.1), and Bundler cannot
continue.
Make sure that `gem install nokogiri -v '1.7.0.1'` succeeds before bundling.
The command "bundle install --path=vendor/bundle --retry=3 --jobs=3" failed and exited with 5 during .
```

**Comment by yosiat** [comment]
@bf4 it looks like the problem is still on master as well.
I am going to submit pull requests to improve performance and base them on this branch.

**Comment by bf4** [comment]
@yosiat wanna take a look at https://github.com/rails-api/active_model_serializers/pull/2071 ?

**Comment by yosiat** [comment]
@bf4 I rebased, now everything passes.

**Comment by bf4** [comment]
@yosiat Can you note which refs you ran the benchmark on and what command you ran?

**Comment by yosiat** [comment]
@bf4 I re-ran the benchmarks on the latest commit,
and this the results -
```
Single: DefaultSerializer 27187.81605082212/ips; 76 objects
ArraySerializer 14801.533415649765/ips; 130 objects
ArraySerializer: each_serializer: DefaultSerializer 18183.121244296395/ips; 122 objects
FlatAuthorSerializer 27428.579553421765/ips; 85 objects
ArraySerializer: each_serializer: FlatAuthorSerializer 19851.039107119468/ips; 114 objects
AuthorWithDefaultRelationshipsSerializer 320.3709843154593/ips; 6190 objects
ArraySerializer: each_serializer: AuthorWithDefaultRelationshipsSerializer 331.79400564626474/ips; 6219 objects
```

**Pull request merged**
