### PR TITLE
Test Rails 6.1

### PR DESCRIPTION
**Pull request by bf4**
#### Purpose

1. Demonstrate the isolated test failures against Rails 6.1
1. Start making non-head support of Rails 6.1 explicit
1. Test configurations for different required Bundler versions

 #### Changes

 #### Caveats

This is sort of a stub. I don't expect to come back and finish it. Anyone can pick it up or make PRs into it.

 #### Related GitHub issues

 #### Additional helpful information

### CODE REVIEW

**Comment by kwent** [comment]
@bf4 6.1 is finally out ! Is this ready for prime time ?

**Comment by bf4** [comment]
I sort of think at this point we should throw out Travis and switch to GitHub action.

But in any case, the isolated tests on Rails 6.1 do fail

```sh
(export RAILS_VERSION=6.1.0;  bundle check || bundle; bundle exec rake)
```

probably isn't anything too complicated, but should be looked at

```
Failure:
JsonApiRendererTest::WithoutRenderer#test_jsonapi_renderer_not_registered [test/active_model_serializers/register_jsonapi_renderer_test_isolated.rb:89]:
--- expected
+++ actual
@@ -1 +1,265 @@
-""
+"<!DOCTYPE html>
+<html lang=\"en\">
+<head>
+  <meta charset=\"utf-8\" />
+  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">
+  <title>Action Controller: Exception caught</title>
+  <style>
+    body {
+      background-color: #FAFAFA;
+      color: #333;
+      color-scheme: light dark;
+      supported-color-schemes: light dark;
+      margin: 0px;
+    }
+
+    body, p, ol, ul, td {
+      font-family: helvetica, verdana, arial, sans-serif;
+      font-size:   13px;
+      line-height: 18px;
+    }
+
+    pre {
+      font-size: 11px;
+      white-space: pre-wrap;
+    }
+
+    pre.box {
+      border: 1px solid #EEE;
+      padding: 10px;
+      margin: 0px;
+      width: 958px;
+    }
+
+    header {
+      color: #F0F0F0;
+      background: #C00;
+      padding: 0.5em 1.5em;
+    }
+
+    h1 {
+      overflow-wrap: break-word;
+      margin: 0.2em 0;
+      line-height: 1.1em;
+      font-size: 2em;
+    }
+
+    h2 {
+      color: #C00;
+      line-height: 25px;
+    }
+
+    .exception-message {
+      padding: 8px 0;
+    }
+
+    .exception-message .message{
+      margin-bottom: 8px;
+      line-height: 25px;
+      font-size: 1.5em;
+      font-weight: bold;
+      color: #C00;
+    }
+
+    .details {
+      border: 1px solid #D0D0D0;
+      border-radius: 4px;
+      margin: 1em 0px;
+      display: block;
+      max-width: 978px;
+    }
+
+    .summary {
+      padding: 8px 15px;
+      border-bottom: 1px solid #D0D0D0;
+      display: block;
+    }
+
+    .details pre {
+      margin: 5px;
+      border: none;
+    }
+
+    #container {
+      box-sizing: border-box;
+      width: 100%;
+      padding: 0 1.5em;
+    }
+
+    .source * {
+      margin: 0px;
+      padding: 0px;
+    }
+
+    .source {
+      border: 1px solid #D9D9D9;
+      background: #ECECEC;
+      max-width: 978px;
+    }
+
+    .source pre {
+      padding: 10px 0px;
+      border: none;
+    }
+
+    .source .data {
+      font-size: 80%;
+      overflow: auto;
+      background-color: #FFF;
+    }
+
+    .info {
+      padding: 0.5em;
+    }
+
+    .source .data .line_numbers {
+      background-color: #ECECEC;
+      color: #AAA;
+      padding: 1em .5em;
+      border-right: 1px solid #DDD;
+      text-align: right;
+    }
+
+    .line {
+      padding-left: 10px;
+      white-space: pre;
+    }
+
+    .line:hover {
+      background-color: #F6F6F6;
+    }
+
+    .line.active {
+      background-color: #FCC;
+    }
+
+    .button_to {
+      display: inline-block;
+      margin-top: 0.75em;
+      margin-bottom: 0.75em;
+    }
+
+    .hidden {
+      display: none;
+    }
+
+    input[type=\"submit\"] {
+      color: white;
+      background-color: #C00;
+      border: none;
+      border-radius: 12px;
+      box-shadow: 0 3px #F99;
+      font-size: 13px;
+      font-weight: bold;
+      margin: 0;
+      padding: 10px 18px;
+      -webkit-appearance: none;
+    }
+    input[type=\"submit\"]:focus,
+    input[type=\"submit\"]:hover {
+      opacity: 0.8;
+    }
+    input[type=\"submit\"]:active {
+      box-shadow: 0 2px #F99;
+      transform: translateY(1px)
+    }
+
+
+    a { color: #980905; }
+    a:visited { color: #666; }
+    a.trace-frames {
+      color: #666;
+      overflow-wrap: break-word;
+    }
+    a:hover { color: #C00; }
+    a.trace-frames.selected { color: #C00 }
+
+    @media (prefers-color-scheme: dark) {
+      body {
+        background-color: #222;
+        color: #ECECEC;
+      }
+
+      .details {
+        border-color: #666;
+      }
+
+      .summary {
+        border-color: #666;
+      }
+
+      .source {
+        border-color: #555;
+        background-color: #333;
+      }
+
+      .source .data {
+        background: #444;
+      }
+
+      .source .data .line_numbers {
+        background: #333;
+        border-color: #222;
+      }
+
+      .line:hover {
+        background: #666;
+      }
+
+      .line.active {
+        background-color: #900;
+      }
+
+      input[type=\"submit\"] {
+        box-shadow: 0 3px #800;
+      }
+      input[type=\"submit\"]:active {
+        box-shadow: 0 2px #800;
+      }
+
+      a { color: #C00; }
+      a.trace-frames { color: #999; }
+      a:hover { color: #E9382B; }
+      a.trace-frames.selected { color: #E9382B; }
+    }
+
+
+  </style>
+
+  <script>
+    var toggle = function(id) {
+      var s = document.getElementById(id).style;
+      s.display = s.display == 'none' ? 'block' : 'none';
+      return false;
+    }
+    var show = function(id) {
+      document.getElementById(id).style.display = 'block';
+    }
+    var hide = function(id) {
+      document.getElementById(id).style.display = 'none';
+    }
+    var toggleTrace = function() {
+      return toggle('blame_trace');
+    }
+    var toggleSessionDump = function() {
+      return toggle('session_dump');
+    }
+    var toggleEnvDump = function() {
+      return toggle('env_dump');
+    }
+  </script>
+</head>
+<body>
+
+<header>
+  <h1>Blocked host: www.example.com</h1>
+</header>
+<div id=\"container\">
+  <h2>To allow requests to www.example.com, add the following to your environment configuration:</h2>
+  <pre>config.hosts &lt;&lt; \"www.example.com\"</pre>
+</div>
+
+
+</body>
+</html>
+"



rails test test/active_model_serializers/register_jsonapi_renderer_test_isolated.rb:85
```

**Comment by bf4** [comment]
seems the grape integration is broken. it should really be it's own gem anyhow

```

rails test /Users/benjamin/files/dev/repos/active_model_serializers/test/grape_test.rb:116

W, [2020-12-10T23:59:09.881450 #15235]  WARN -- : You are setting a key that conflicts with a built-in method Hashie::Mash#size defined in Hash. This can cause unexpected behavior when accessing the key as a property. You can still access the key via the #[] method.
W, [2020-12-10T23:59:09.881535 #15235]  WARN -- : You are setting a key that conflicts with a built-in method Hashie::Mash#size defined in Hash. This can cause unexpected behavior when accessing the key as a property. You can still access the key via the #[] method.
W, [2020-12-10T23:59:09.881654 #15235]  WARN -- : You are setting a key that conflicts with a built-in method Hashie::Mash#size defined in Hash. This can cause unexpected behavior when accessing the key as a property. You can still access the key via the #[] method.
W, [2020-12-10T23:59:09.881737 #15235]  WARN -- : You are setting a key that conflicts with a built-in method Hashie::Mash#size defined in Hash. This can cause unexpected behavior when accessing the key as a property. You can still access the key via the #[] method.
E

Error:
ActiveModelSerializers::GrapeTest#test_implicit_formatter_handles_collections:
NoMethodError: undefined method `[]' for nil:NilClass
```

**Comment by bf4** [comment]
Ok, I'm done poking at this for real

**Comment by bf4** [comment]
Superseded by https://github.com/rails-api/active_model_serializers/pull/2403

**Pull request closed without merging**
