### PR TITLE
support custom options for relections

### PR DESCRIPTION
**Pull request by LcpMarvel**
Support the DSL like below.
```ruby
class PostSerializer < ActiveModel::Serializer
  belongs_to :author, serializer: AuthorSerializer, custom_options: :author
  has_many :comments, serializer: CommentSerializer, custom_options: :comments
end
```

```ruby
class AuthorSerializer < ActiveModel::Serializer
  def custom_options
    instance_options[:reflection_options]  # => { custom_options: :author }
  end
end

class CommentSerializer < ActiveModel::Serializer
  def custom_options
    instance_options[:reflection_options]  # => { custom_options: :comments }
  end
end
```

### CODE REVIEW

**Comment by bf4** [comment]
@LcpMarvel Thanks for this and for the test, but I'm unsure what it does.  (There's no assertion in the test).

**Comment by LcpMarvel** [comment]
I can pass objects through the associations rather than passing them in controller.

**Comment by bf4** [comment]
`virtual_value` does that. See e.g. https://github.com/rails-api/active_model_serializers/blob/f562449bd439d1295b91b41b01d5b780c793100a/test/fixtures/poro.rb#L218-L222

**Comment by bf4** [comment]
You can also use the block syntax if you're on master

**Comment by LcpMarvel** [comment]
thx

**Comment by bf4** [comment]
@LcpMarvel please report back here what worked for you :). Glad I could help

**Pull request closed without merging**
