### PR TITLE
organize badges

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
#### Purpose

Badges need to be organized a bit better.

#### Changes

only to readme

#### Related GitHub issues

#1551

### CODE REVIEW

**Comment by groyoh** [comment]
:100:

**Comment by remear** [comment]
Looks good.

**Comment by groyoh** [comment]
Changelog was forgotten :wink:

**Comment by NullVoxPopuli** [comment]
Did we really need it for something like this?

**Comment by groyoh** [comment]
My bad, I thought that this PR also added the codebeat badge. But I assume that #1551 should have had an entry in the CHANGELOG stating that we added codebeat, right?

**Comment by remear** [comment]
I figured the CHANGELOG was more for the proejct's code changes and this was just a tooling addition. Travis is mentioned in there though, so sure, it could use a CHANGELOG entry.

**Comment by bf4** [comment]
@remear @groyoh some of the changelog was auto-generated and not gardened.  I also like to give non-maintainers credit for their work in it.

**Comment by groyoh** [comment]
@remear an entry for tooling could also be an easy way to figure out why this tool was added in the first place.

**Pull request merged**
