### PR TITLE
Move from ActiveModelSerializers::Model to ActiveModel::Serializer::Model

### PR DESCRIPTION
**Pull request by maurogeorge**
Hi guys,

Today the `ActiveModelSerializers::Model` is the only public API under this namespace.

To keep consistency move to `ActiveModel::Serializer::Model`.

Makes sense to you?

Thanks

### CODE REVIEW

**Comment by bf4** [comment]
I put it there on purpose, see (ongoing) discussion of the reasons in https://github.com/rails-api/active_model_serializers/issues/1298

Holding this for now

**Comment by NullVoxPopuli** [comment]
@maurogeorge I think the consensus was to use `ActiveModel::Serializers::_____`, so-- can you update this PR, accordingly?

**Comment by bf4** [comment]
Consensus?  

B mobile phone

**Comment by bf4** [comment]
Should we rename the gem, too, then?

B mobile phone

**Comment by NullVoxPopuli** [comment]
@bf4 
 - https://github.com/rails-api/active_model_serializers/pull/1310#discussion_r43813265
 - https://github.com/rails-api/active_model_serializers/pull/1310#issuecomment-153510266 (kinda)
 - https://github.com/rails-api/active_model_serializers/pull/1310#discussion_r43814902

The gem is already active_model_serializers, which I think fits well with ActiveModel::Serializers::___

**Comment by maurogeorge** [comment]
@NullVoxPopuli thanks for the feedback. I will wait for a feedback of the team https://github.com/rails-api/active_model_serializers/pull/1310#issuecomment-153869492 and when we have in the same page I will work on it.

**Comment by bf4** [comment]
But the gem is not activemodel::serializers and rails has that namespace already

B mobile phone

**Comment by bf4** [comment]
This can't be merged until https://github.com/rails-api/active_model_serializers/pull/1310 is resolved

Changing the gem name is a pretty big deal, as is piggy-backing on existing rails namespaces

**Comment by NullVoxPopuli** [comment]
the rails namespace is a module, which is fine.
as long as we keep the ...::Serializers a module, they can co-exist

**Comment by bf4** [comment]
Closing as resolved in #1310

**Comment by maurogeorge** [comment]
:+1:

**Pull request closed without merging**
