### PR TITLE
Favor ActiveSupport::TestCase over Minitest::Test

### PR DESCRIPTION
**Pull request by bf4**
- Better minitest 4/5 support
- Better DSL
- Already available with no changes
- Consistent interface

### CODE REVIEW

**Comment by beauby** [comment]
What would be the drawbacks?

**Comment by bf4** [comment]
@beauby I have no idea what the drawback would be.  I do know that at one point AS::TC was removed in favor of raw minitest.  Perhaps speed?

**Comment by beauby** [comment]
After investigating a bit, it appears `ActiveSupport::TestCase` is just an extension of `Minitest::Test`, so this PR should not be an issue. I'll merge it tomorrow unless somebody raises their voice.

**Comment by spastorino** [comment]
It's ok to merge this, when I was building AMS 0.10 I used Minitest::Test just because I didn't need AS::TC and wanted to depend as minimum as possible on Rails stuff.

**Comment by beauby** [comment]
Great, thanks for the heads up @spastorino. As 0.10 is already depending on quite a bit of rails stuff, I don't believe this PR will hurt much, so I'm merging.

**Pull request merged**
