### PR TITLE
Add warning in caching documentation

### PR DESCRIPTION
**Pull request by aldreth**
References https://github.com/rails-api/active_model_serializers/issues/1587

### CODE REVIEW

**Comment by bf4** [comment]
Awesome, thanks!

**Comment by bf4** [comment]
(The caching issues are actually not so bad at present. I've done a lot of work on them and they should generally be positive at this point, but not as good as they should be)

**Comment by aldreth** [comment]
Yeah, they hit an app I'm working on pretty hard, so I've been following progress with interest.

**Comment by bf4** [comment]
@aldreth Thanks.  I've been mostly thinking about simplifying AMS internals for the push to 1.0 and that will likely include having caching as a separate layer, so that it will be easier to manage.  In the meantime, I haven't been working on that area. If you're interested I can give you a bit of a tour.

**Pull request merged**
