### PR TITLE
Add some failing tests around has_many assocs ..where no serializer is defined for the thing that is has_many'd

### PR DESCRIPTION
**Pull request by JustinAiken**
As requested in #877

### CODE REVIEW

**Comment by JustinAiken** [comment]
The three tests are probably redundant, but I can remove which ever ones aren't helpful.

**Comment by joaomdmoura** [comment]
Great @JustinAiken, now we can keep working into this branch using the tests as reference :smile:

**Comment by bf4** [comment]
In looking at this, is the problem that we have a record with a serializer, and one of its associations has a an enumerable object such as an array of hash whose elements don't implement ActiveModel::Serialization? So is the problem in not having a pass-through-serializer that arrayserializer can call or in calling the array serializer in the first place?  I'm been playing with this a bit, and think it might just be better to not use AMS to serialize objects that it doesn't know how to serialize... that's the renderer's job, no?

**Comment by bf4** [comment]
This works inasmuch as it doesn't crash, but I'm not sure if the end behavior is what we want https://github.com/rails-api/active_model_serializers/commit/56a7bd1b6dd9f083b0f3a9d6d24e9dc85efbffac fwiw

**Comment by bf4** [comment]
The commit in this PR is now included in #962. Propose closing (and thanks!) :smile:

**Comment by joaomdmoura** [comment]
Just waiting the merge before closing all issues related to it @bf4

**Pull request closed without merging**
