### PR TITLE
Allow users to globally opt out of automatic serializer lookup

### PR DESCRIPTION
**Pull request by bf4**
Closes https://github.com/rails-api/active_model_serializers/pull/1295

### CODE REVIEW

**Comment by bf4** [comment]
@trek does this work for you?

**Comment by beauby** [comment]
One possible solution is to simply monkey-patch `ActiveModel::Serializer`'s `serializer_lookup_chain_for` method to return an empty array.

**Comment by trek** [comment]
Sorry for taking so long to verify this. Just bundled and ran our suite. Totally works.

**Comment by trek** [comment]
I've closed #1295 in favor of this.

**Comment by bf4** [comment]
Merged!

**Comment by trek** [comment]
So, it turns out there are some subtle differences between this and #1295. This ignores custom `adapter` configured with `ActiveModel::Serializer.config.adapter` when serializing associations inside the root object.

**Comment by bf4** [comment]
weird.  Can you provide some failing data for that?

**Comment by trek** [comment]
@bf4 sorry for the delay: https://github.com/rails-api/active_model_serializers/issues/1500

**Pull request merged**
