### PR TITLE
Update CHANGELOG.md using `github-changes`

### PR DESCRIPTION
**Pull request by bf4**

### CODE REVIEW

**Comment by bf4** [comment]
An advantage of merging this now and cleaning it up later is that it will encourage prs, in the meantime, to use the 'new' format that references the pr

**Comment by bf4** [comment]
Any objections? @rails-api/ams

**Comment by NullVoxPopuli** [comment]
Is this a format we manually keep up to date on master?

I do like that it references the github PR

**Comment by bf4** [comment]
I could be.  Pretty easy to parse

**Comment by NullVoxPopuli** [comment]
well, I'm in favor! :+1:

**Comment by beauby** [comment]
LGTM, merging.

**Pull request merged**
