### PR TITLE
Change 'belongs_to' in README for 'has_one' (see #648)

### PR DESCRIPTION
**Pull request by gnapse**

### CODE REVIEW

**Comment by JoshSmith** [comment]
:+1:

**Comment by JoshSmith** [comment]
@joaomdmoura looks good to me, but I'd appreciate another :+1: if it is.

**Comment by joaomdmoura** [comment]
It started at #648 
After reading it I don't think it's the right solution.
As was mentioned, at [previous](https://github.com/rails-api/active_model_serializers/tree/0-9-2) versions of AMS belongs_to wasn't supported

> Serializers are only concerned with multiplicity, and not ownership. belongs_to ActiveRecord associations can be included using has_one in your serializer.

The master README represents a reference to 0.10.0 version and it supports ```belongs_to```:

> The generated seralizer will contain basic `attributes` and `has_many`/`has_one`/`belongs_to` declarations, based on the model.

One of the key points on AMS is to follow Rails conventions, so I really appreciate to keep this kind of *syntax sugars*

Some of the lines updated on this PR are an practical example using ```PostSerializer``` and  ```CommentSerializer```

```ruby
class PostSerializer < ActiveModel::Serializer
  cache key: 'posts', expires_in: 3.hours
  attributes :title, :body

  has_many :comments

  url :post
end
```

```ruby
class CommentSerializer < ActiveModel::Serializer
  attributes :name, :body

  belongs_to :post

  url [:post, :comment]
end
```

They already have the usual ```has_many - belongs_to``` relationship. Use the same syntax to AMS make it a lot easier to understand. Because of that I'm not sure if this PR should be merged. Hope it makes sense.

I think that the problem pointed out at #648 is related to a miss understanding that the master now representes a new implementation. Maybe we could try to point it out at the README that it's for 0.10.0.

**Comment by JoshSmith** [comment]
Ah, I see. Thanks for the clarification @joaomdmoura. I'd misunderstood.

I feel that this should not be merged in that case, as it's not reflective of what's actually happening.

@gnapse appreciate the PR, but does this clarify things?

**Comment by gnapse** [comment]
I only submitted this PR because the library did not support `belongs_to` previously, yet the README file had an example using it. I think at the time I did it, the version supporting it was not yet released as stable, and I was confused to see the example in the README, but it didn't work for me on the latest stable version at the time.

However I agree with @joaomdmoura that it should be supported. It's clearer to mimic the semantics of the underlaying data models, even if this library is not concerned with ownership, but plurality. I'm glad that it was added to more recent versions. In that case it's ok to disregard this PR completely.

**Comment by JoshSmith** [comment]
Thanks @gnapse. I think we'll go ahead and close this then.

**Pull request closed without merging**
