### PR TITLE
class_methods

### PR DESCRIPTION
**Pull request by martinezcoder**
#### Purpose

Improve code using [ActiveSuppor::Concern]( http://api.rubyonrails.org/classes/ActiveSupport/Concern.html)

#### Related GitHub issues

https://github.com/rails-api/active_model_serializers/issues/1748

#### Additional helpful information

http://api.rubyonrails.org/classes/ActiveSupport/Concern.html

### CODE REVIEW

**Comment by NullVoxPopuli** [comment]
according to travis, this doesn't work with rails 4.1 :-\

**Comment by NullVoxPopuli** [comment]
closing, cause of rails 4.1 incompatibility

**Comment by bf4** [comment]
@martinezcoder thanks for this!  If you're looking for more stuff of this sort to help out with, maybe take a look at our rubocop todo's, and pick one?

**Comment by martinezcoder** [comment]
yes, I'll do! thanks and sorry for the inconvenience in my PR

**Pull request closed without merging**
