### PR TITLE
Add test coverage; account for no artifacts on CI

### PR DESCRIPTION
**Pull request by bf4**
Requires https://github.com/rails-api/active_model_serializers/pull/1109

### CODE REVIEW

**Comment by bf4** [comment]
Failures were in jruby and rbx because they do coverage differently and had a lower minimum coverage... I'm considering lowering it overall, or perhaps having an implementation-specific coverage minimum?  In any case, the PR works

**Comment by joaomdmoura** [comment]
Despite of being simple the `.simplecov` looks a little bit tricky to me.
I'm okay with lowering it overall, I think the goal here is to give us the bigger picture and keep track of it.

**Comment by bf4** [comment]
Yup. Will do

**Comment by bf4** [comment]
@joaomdmoura Improved, the one failure is rbx, just needs to be restarted

**Comment by joaomdmoura** [comment]
restarting

**Comment by bf4** [comment]
Rebased and rubocoped

**Pull request merged**
