### PR TITLE
Add raise_cannot_infer_root_key_error to config

### PR DESCRIPTION
**Pull request by tashirosota**
#### Purpose
 - Raise error when cannot infer root key by v10.0.7 . I think this is braking change. 
 - Added config that you can upgrade without changing existing code.

#### Changes
 - ArgumentError changes to CannotInferRootKeyError in CollectionSerializer#json_key
    - Custom error helps clarify the problem
 - Add config.raise_cannot_infer_root_key_error
 - Add test when serializer does not have type and collection is empty

#### Related GitHub issues
 - https://github.com/rails-api/active_model_serializers/issues/2406

#### 
Our project has many like this code😢

```
::ActiveModelSerializers::SerializableResource.new(
  collections, # [] empty array
  each_serializer: NonTypeCollectionSerializer,
).serializable_hash || []
※ v0.10.6
```

### CODE REVIEW

**Comment by wasifhossain** [comment]
Looks good to me

**Comment by tashirosota** [comment]
@wasifhossain 
Will this PR be merged?

**Comment by wasifhossain** [comment]
let's do this

**Comment by wasifhossain** [comment]
thanks for the reminder!

**Comment by mvz** [comment]
This doesn't seem to resolve the problem that this error is *also* raised when `each_serializer` is specified, even though specifying an `each_serializer` is suggested as a way to resolve the error.

**Comment by tashirosota** [comment]
@mvz 
When each_serializer is specified and don't want to make an error.
Can set `ActiveModelSerializers.config.raise_cannot_infer_root_key_error = true` and not raise error.
This error coused when each_serializer is specified and (serializer's type is null || collection is empty || root key is null), it is correct behavior, but braking change.
So I patched this option, resolve to this case < v0.10.6

```
::ActiveModelSerializers::SerializableResource.new(
  collections, # [] empty array
  each_serializer: NonTypeCollectionSerializer,
).serializable_hash || []
```

**Pull request merged**
