### PR TITLE
Remove legacy method accidentally reintroduced in #1017

### PR DESCRIPTION
**Pull request by beauby**

### CODE REVIEW

**Comment by NullVoxPopuli** [comment]
silly, #1017 


:+1:

**Comment by joaomdmoura** [comment]
Nice :smile:

**Comment by bf4** [comment]
I could have sworn I made a pr to fix this... Good catch all the same

**Comment by bf4** [comment]
Ah, found it in https://github.com/rails-api/active_model_serializers/pull/1117 didn't make a standalone-pr it appears.. was part of my rebasing it against master... https://github.com/rails-api/active_model_serializers/commit/b592ebc2db2331714ed91a125c722cc5132d5257

**Pull request merged**
