### PR TITLE
Adding appveyor to the project

### PR DESCRIPTION
**Pull request by joaomdmoura**
`appveyor` is a well known service that enable us to test AMS on windows environments in order to make sure we are supporting developers that use windows.

### CODE REVIEW

**Comment by joaomdmoura** [comment]
I'm still working on this, I don't think it will pass on this first attempt, this `appveyor` setting might be a little tricky.
If you have some expertise here make yourself comfortable to help by commenting or sending a PR to `appveyor` branch.

**Comment by Eric-Guo** [comment]
I try to build at [appveyor](https://ci.appveyor.com/project/Eric-Guo/active-model-serializers/build/4) several time using this branch, except ruby 2.2, all works, for ruby 2.2, it stop at gem install bundler, long time, I already open [tickets 2867](http://help.appveyor.com/discussions/problems/2867-ruby-pre-install-bundler-on-all-versions-2nd-time) to appveyor.

**Comment by joaomdmoura** [comment]
Yup, I think that even so we are good to go, I'm removing 2.2 for now in order to merge it, please keep this up to date with the ticket you opened :smile:

**Comment by Eric-Guo** [comment]
:+1:

**Pull request merged**
