### PR TITLE
resolve collection cache error

### PR DESCRIPTION
**Pull request by quake**
cache_read_multi result should be passed to *options*

### CODE REVIEW

**Comment by bf4** [comment]
@quake would you mind elaborating on what the bug is and how it plays out? That the adapter options are considered first before the 'serialization' options?

**Comment by quake** [comment]
@bf4 I encountered the bug that collection cache doesn't work, after checking the cache log, I find that serializer reads the *cached_attributes* from second options:
https://github.com/rails-api/active_model_serializers/blob/0-10-stable/lib/active_model/serializer.rb#L389

**Comment by bf4** [comment]
<table>
<thead>
<th>before</th><th>after</th>
</thead>
<tbody>
<tr><td>
<pre>
AR: attributes 14306.031185895226/ips; 110 objects
AR: json 12823.174957439756/ips; 110 objects
AR: JSON API 11907.125594768599/ips; 110 objects
Benchmark results:
{
  "commit_hash": "0-10-stable",
  "version": "0.10.7",
  "rails_version": "4.2.10",
  "benchmark_run[environment]": "2.4.1p111",
  "runs": [
    {
      "benchmark_type[category]": "AR: attributes",
      "benchmark_run[result][iterations_per_second]": 14306.031,
      "benchmark_run[result][total_allocated_objects_per_iteration]": 110
    },
    {
      "benchmark_type[category]": "AR: json",
      "benchmark_run[result][iterations_per_second]": 12823.175,
      "benchmark_run[result][total_allocated_objects_per_iteration]": 110
    },
    {
      "benchmark_type[category]": "AR: JSON API",
      "benchmark_run[result][iterations_per_second]": 11907.126,
      "benchmark_run[result][total_allocated_objects_per_iteration]": 110
    }
  ]
}
attributes 950.3910286334177/ips; 2625 objects
json_api 279.0329869268122/ips; 4048 objects
json 746.9483984217126/ips; 2682 objects
Benchmark results:
{
  "commit_hash": "0-10-stable",
  "version": "0.10.7",
  "rails_version": "4.2.10",
  "benchmark_run[environment]": "2.4.1p111",
  "runs": [
    {
      "benchmark_type[category]": "attributes",
      "benchmark_run[result][iterations_per_second]": 950.391,
      "benchmark_run[result][total_allocated_objects_per_iteration]": 2625
    },
    {
      "benchmark_type[category]": "json_api",
      "benchmark_run[result][iterations_per_second]": 279.033,
      "benchmark_run[result][total_allocated_objects_per_iteration]": 4048
    },
    {
      "benchmark_type[category]": "json",
      "benchmark_run[result][iterations_per_second]": 746.948,
      "benchmark_run[result][total_allocated_objects_per_iteration]": 2682
    }
  ]
}







caching on: caching serializers: gc off 925.635250535409/ips; 1385 objects
caching on: fragment caching serializers: gc off 942.3165851399872/ips; 1486 objects
caching on: non-caching serializers: gc off 1084.994624726056/ips; 1323 objects
caching off: caching serializers: gc off 1005.4813948694199/ips; 1385 objects
caching off: fragment caching serializers: gc off 950.1102682941865/ips; 1486 objects
caching off: non-caching serializers: gc off 1083.3262574058942/ips; 1323 objects
Benchmark results:
{
  "commit_hash": "0-10-stable",
  "version": "0.10.7",
  "rails_version": "4.2.10",
  "benchmark_run[environment]": "2.4.1p111",
  "runs": [
    {
      "benchmark_type[category]": "caching on: caching serializers: gc off",
      "benchmark_run[result][iterations_per_second]": 925.635,
      "benchmark_run[result][total_allocated_objects_per_iteration]": 1385
    },
    {
      "benchmark_type[category]": "caching on: fragment caching serializers: gc off",
      "benchmark_run[result][iterations_per_second]": 942.317,
      "benchmark_run[result][total_allocated_objects_per_iteration]": 1486
    },
    {
      "benchmark_type[category]": "caching on: non-caching serializers: gc off",
      "benchmark_run[result][iterations_per_second]": 1084.995,
      "benchmark_run[result][total_allocated_objects_per_iteration]": 1323
    },
    {
      "benchmark_type[category]": "caching off: caching serializers: gc off",
      "benchmark_run[result][iterations_per_second]": 1005.481,
      "benchmark_run[result][total_allocated_objects_per_iteration]": 1385
    },
    {
      "benchmark_type[category]": "caching off: fragment caching serializers: gc off",
      "benchmark_run[result][iterations_per_second]": 950.11,
      "benchmark_run[result][total_allocated_objects_per_iteration]": 1486
    },
    {
      "benchmark_type[category]": "caching off: non-caching serializers: gc off",
      "benchmark_run[result][iterations_per_second]": 1083.326,
      "benchmark_run[result][total_allocated_objects_per_iteration]": 1323
    }
  ]
}
Configurable Lookup Chain 2034.4894307726884/ips; 760 objects
Old Lookup Chain (v0.10) 1865.5007490355947/ips; 760 objects
Benchmark results:
{
  "commit_hash": "0-10-stable",
  "version": "0.10.7",
  "rails_version": "4.2.10",
  "benchmark_run[environment]": "2.4.1p111",
  "runs": [
    {
      "benchmark_type[category]": "Configurable Lookup Chain",
      "benchmark_run[result][iterations_per_second]": 2034.489,
      "benchmark_run[result][total_allocated_objects_per_iteration]": 760
    },
    {
      "benchmark_type[category]": "Old Lookup Chain (v0.10)",
      "benchmark_run[result][iterations_per_second]": 1865.501,
      "benchmark_run[result][total_allocated_objects_per_iteration]": 760
    }
  ]
}
camel 7265.22609369836/ips; 189 objects
camel_lower 6669.692611642767/ips; 189 objects
dash 6541.666355813773/ips; 189 objects
unaltered 7708243.4607046805/ips; 1 objects
underscore 5735.861045830341/ips; 189 objects
Benchmark results:
{
  "commit_hash": "0-10-stable",
  "version": "0.10.7",
  "rails_version": "4.2.10",
  "benchmark_run[environment]": "2.4.1p111",
  "runs": [
    {
      "benchmark_type[category]": "camel",
      "benchmark_run[result][iterations_per_second]": 7265.226,
      "benchmark_run[result][total_allocated_objects_per_iteration]": 189
    },
    {
      "benchmark_type[category]": "camel_lower",
      "benchmark_run[result][iterations_per_second]": 6669.693,
      "benchmark_run[result][total_allocated_objects_per_iteration]": 189
    },
    {
      "benchmark_type[category]": "dash",
      "benchmark_run[result][iterations_per_second]": 6541.666,
      "benchmark_run[result][total_allocated_objects_per_iteration]": 189
    },
    {
      "benchmark_type[category]": "unaltered",
      "benchmark_run[result][iterations_per_second]": 7708243.461,
      "benchmark_run[result][total_allocated_objects_per_iteration]": 1
    },
    {
      "benchmark_type[category]": "underscore",
      "benchmark_run[result][iterations_per_second]": 5735.861,
      "benchmark_run[result][total_allocated_objects_per_iteration]": 189
    }
  ]
}
</pre>
</td><td>
<pre>
AR: attributes 13886.236342908565/ips; 110 objects
AR: json 12720.462195124863/ips; 110 objects
AR: JSON API 12761.075572144222/ips; 110 objects
Benchmark results:
{
  "commit_hash": "quake-collection_cache",
  "version": "0.10.7",
  "rails_version": "4.2.10",
  "benchmark_run[environment]": "2.4.1p111",
  "runs": [
    {
      "benchmark_type[category]": "AR: attributes",
      "benchmark_run[result][iterations_per_second]": 13886.236,
      "benchmark_run[result][total_allocated_objects_per_iteration]": 110
    },
    {
      "benchmark_type[category]": "AR: json",
      "benchmark_run[result][iterations_per_second]": 12720.462,
      "benchmark_run[result][total_allocated_objects_per_iteration]": 110
    },
    {
      "benchmark_type[category]": "AR: JSON API",
      "benchmark_run[result][iterations_per_second]": 12761.076,
      "benchmark_run[result][total_allocated_objects_per_iteration]": 110
    }
  ]
}
attributes 969.1184127987731/ips; 2622 objects
json_api 283.3807974124061/ips; 4048 objects
json 780.802661212277/ips; 2679 objects
Benchmark results:
{
  "commit_hash": "quake-collection_cache",
  "version": "0.10.7",
  "rails_version": "4.2.10",
  "benchmark_run[environment]": "2.4.1p111",
  "runs": [
    {
      "benchmark_type[category]": "attributes",
      "benchmark_run[result][iterations_per_second]": 969.118,
      "benchmark_run[result][total_allocated_objects_per_iteration]": 2622
    },
    {
      "benchmark_type[category]": "json_api",
      "benchmark_run[result][iterations_per_second]": 283.381,
      "benchmark_run[result][total_allocated_objects_per_iteration]": 4048
    },
    {
      "benchmark_type[category]": "json",
      "benchmark_run[result][iterations_per_second]": 780.803,
      "benchmark_run[result][total_allocated_objects_per_iteration]": 2679
    }
  ]
}







caching on: caching serializers: gc off 989.7750481711399/ips; 1370 objects
caching on: fragment caching serializers: gc off 963.5826287408387/ips; 1471 objects
caching on: non-caching serializers: gc off 1098.2599364414848/ips; 1320 objects
caching off: caching serializers: gc off 1029.1350920322554/ips; 1370 objects
caching off: fragment caching serializers: gc off 967.2609875276349/ips; 1471 objects
caching off: non-caching serializers: gc off 1085.2177265220494/ips; 1320 objects
Benchmark results:
{
  "commit_hash": "quake-collection_cache",
  "version": "0.10.7",
  "rails_version": "4.2.10",
  "benchmark_run[environment]": "2.4.1p111",
  "runs": [
    {
      "benchmark_type[category]": "caching on: caching serializers: gc off",
      "benchmark_run[result][iterations_per_second]": 989.775,
      "benchmark_run[result][total_allocated_objects_per_iteration]": 1370
    },
    {
      "benchmark_type[category]": "caching on: fragment caching serializers: gc off",
      "benchmark_run[result][iterations_per_second]": 963.583,
      "benchmark_run[result][total_allocated_objects_per_iteration]": 1471
    },
    {
      "benchmark_type[category]": "caching on: non-caching serializers: gc off",
      "benchmark_run[result][iterations_per_second]": 1098.26,
      "benchmark_run[result][total_allocated_objects_per_iteration]": 1320
    },
    {
      "benchmark_type[category]": "caching off: caching serializers: gc off",
      "benchmark_run[result][iterations_per_second]": 1029.135,
      "benchmark_run[result][total_allocated_objects_per_iteration]": 1370
    },
    {
      "benchmark_type[category]": "caching off: fragment caching serializers: gc off",
      "benchmark_run[result][iterations_per_second]": 967.261,
      "benchmark_run[result][total_allocated_objects_per_iteration]": 1471
    },
    {
      "benchmark_type[category]": "caching off: non-caching serializers: gc off",
      "benchmark_run[result][iterations_per_second]": 1085.218,
      "benchmark_run[result][total_allocated_objects_per_iteration]": 1320
    }
  ]
}
Configurable Lookup Chain 2116.701684804751/ips; 751 objects
Old Lookup Chain (v0.10) 1881.9882005694822/ips; 751 objects
Benchmark results:
{
  "commit_hash": "quake-collection_cache",
  "version": "0.10.7",
  "rails_version": "4.2.10",
  "benchmark_run[environment]": "2.4.1p111",
  "runs": [
    {
      "benchmark_type[category]": "Configurable Lookup Chain",
      "benchmark_run[result][iterations_per_second]": 2116.702,
      "benchmark_run[result][total_allocated_objects_per_iteration]": 751
    },
    {
      "benchmark_type[category]": "Old Lookup Chain (v0.10)",
      "benchmark_run[result][iterations_per_second]": 1881.988,
      "benchmark_run[result][total_allocated_objects_per_iteration]": 751
    }
  ]
}
camel 7177.394484771248/ips; 189 objects
camel_lower 6490.712139673376/ips; 189 objects
dash 6461.059235047451/ips; 189 objects
unaltered 7700369.02384621/ips; 1 objects
underscore 5805.895811300559/ips; 189 objects
Benchmark results:
{
  "commit_hash": "quake-collection_cache",
  "version": "0.10.7",
  "rails_version": "4.2.10",
  "benchmark_run[environment]": "2.4.1p111",
  "runs": [
    {
      "benchmark_type[category]": "camel",
      "benchmark_run[result][iterations_per_second]": 7177.394,
      "benchmark_run[result][total_allocated_objects_per_iteration]": 189
    },
    {
      "benchmark_type[category]": "camel_lower",
      "benchmark_run[result][iterations_per_second]": 6490.712,
      "benchmark_run[result][total_allocated_objects_per_iteration]": 189
    },
    {
      "benchmark_type[category]": "dash",
      "benchmark_run[result][iterations_per_second]": 6461.059,
      "benchmark_run[result][total_allocated_objects_per_iteration]": 189
    },
    {
      "benchmark_type[category]": "unaltered",
      "benchmark_run[result][iterations_per_second]": 7700369.024,
      "benchmark_run[result][total_allocated_objects_per_iteration]": 1
    },
    {
      "benchmark_type[category]": "underscore",
      "benchmark_run[result][iterations_per_second]": 5805.896,
      "benchmark_run[result][total_allocated_objects_per_iteration]": 189
    }
  ]
}
</pre>
</td></tr>
</tbody>
</table>

**Comment by bf4** [comment]
Closed by  d274295

**Comment by bf4** [comment]
On review, this is a pretty good catch. It's distributing the tests don't catch this.

**Pull request closed without merging**
