### PR TITLE
Refactor JsonApi adapter to avoid redundant computations.

### PR DESCRIPTION
**Pull request by beauby**
This is a rewrite of #1300, stripped down to the bare minimum.

### CODE REVIEW

**Comment by anonova** [comment]
```
rails-api/active_model_serializers:master: [active_model_serializers] Rendered ActiveModel::Serializer::CollectionSerializer with ActiveModel::Serializer::Adapter::JsonApi (2186.42ms)
rails-api/active_model_serializers:master: [active_model_serializers] Rendered ActiveModel::Serializer::CollectionSerializer with ActiveModel::Serializer::Adapter::Attributes (515.21ms)
beauby/active_model_serializers:jsonapi-refactor-2016: [active_model_serializers] Rendered ActiveModel::Serializer::CollectionSerializer with ActiveModel::Serializer::Adapter::JsonApi (1094.52ms)
```

Nice gains! Seeing about a 2x speedup from master with 1457 objects (250 root + 55 references + 1152 included resources). I may do some profiling at some point since this still seems quite slow, but it's definitely better than before.

It's also about 2x slower, rather than 4x, than the attributes adapter now.

**Comment by beauby** [comment]
@anonova Thanks for those numbers! We really need to get that benchmarking PR done soon. In general, I would expect JsonApi to be slower than Attributes, because in case of `has_many` or `has_one` associations, JsonApi will have to access the related models to fill the `relationships` part of the base object with the resource identifiers, even if the associated models are not included, whereas the Attributes adapter will simply skip them. So in the end, the JsonApi adapter is slightly richer, and it would seem more fair to compare JsonApi with nesting level `n` against JsonApi with nesting level `n+1`.
But in any case, we'll make sure the JsonApi adapter gets as fast as possible!

**Comment by beauby** [comment]
Any objection to this @rails-api/ams?

**Comment by bf4** [comment]
Looks good.  @anonova gist or paste bm code w results?

**Comment by kurko** [comment]
LGTM. +2

**Pull request merged**
