### PR TITLE
Failing test for 1211

### PR DESCRIPTION
**Pull request by hut8**
Reproduces this:
#1211 

Throws the same exception :+1: 

Found bugs

### CODE REVIEW

**Comment by NullVoxPopuli** [comment]
yay!! thank you!. 
I'll check in to this in a few hours, unless @beauby beats me to it.

**Comment by NullVoxPopuli** [comment]
I fixed it, I'll push the pr shortly.

**Comment by NullVoxPopuli** [comment]
pushed! #1214

**Comment by beauby** [comment]
@hut8 Awesome that you pinned it down!

**Pull request closed without merging**
