### PR TITLE
Change  'ActiveModelSerializers' to 'ActiveModel::Serializer' in adapters.md

### PR DESCRIPTION
**Pull request by ScottKbka**
Change 'ActiveModelSerializers' to 'ActiveModel::Serializer' to reflect v10.0.rc4

### CODE REVIEW

**Comment by bf4** [comment]
@ScottKbka Thanks for this.  The direction we want to go with the config is actually as specified in the docs.  We're moving away from the ActiveModel::Serializer class as our base namespace https://github.com/rails-api/active_model_serializers/blob/master/docs/rfcs/0000-namespace.md

**Comment by bf4** [comment]
I'm going to close this. Thanks for looking through the docs and making the pr.  It would be helpful to change the link on the README from `rubydoc.info/github/rails-api/active_model_serializers` to `rubydoc.info/github/rails-api/active_model_serializers/v0.10.0.rc4` if you'd like to amend and force push this PR, I'll merge that.

**Comment by ScottKbka** [comment]
Ah, thanks for the explanation @bf4 I made the change to the readme and force pushed, but I don't think I can reopen a PR.

**Comment by bf4** [comment]
Hmm, maybe just make a new pr. :shrug:

**Pull request closed without merging**
