### PR TITLE
codebeat badge

### PR DESCRIPTION
**Pull request by korzonek**
Is it fine to add codebeat badge to README? 

codebeat is automated code review tool for Swift, Ruby & Go that helps get instant feedback on code quality. 

"Quick wins" suggested by codebeat could be a nice candidate for a pull request and help other developers become contributors.

FYI. To be fully open and honest. I'm co-founder of codebeat.

### CODE REVIEW

**Comment by groyoh** [comment]
Could you maybe describe the advantages over code climate?

**Comment by korzonek** [comment]
* _Multi-Language support both for mobile and web_. We implemented all algorithms on our own and we are not dependent on open-source projects like flog, flay etc. It means relatively quickly we can support more languages also where there is no open source projects that can help measure complexity or duplications of code.
* _Quick Wins_. After analysing your project we will suggest you issues in code with the biggest overall impact on your project's health. Try to refactor these hot spots first and see how your GPA improves.
* _Compare Changes_. In the stream of Recent Changes you will be able see what exactly caused your classes to improve or degrade.

**Comment by bf4** [comment]
@korzonek if you did some sort of benchmarking or custom containers that'd be a lot more interesting :)  right now, the service looks nice, but it doesn't seem to (yet?) offer an advantage over or complement to our existing codeclimate config.  

Multi-language isn't really an issue in this project :)

Where are the hotspots? https://codebeat.co/projects/github-com-rails-api-active_model_serializers/ratings

I'm also kind of curious about not using flog, flay, reek, etc.  There's a lot of really great tools already written. https://github.com/metricfu/metric_fu/wiki/Code-Tools

**Comment by korzonek** [comment]
We love tools like flay, flog, rubocop or reek but they are specific to Ruby. 
Because we developed a custom set of language-agnostic algorithms we can offer the exact same functionality for all supported languages - unlike any of our otherwise excellent competitors. 
That, and we can easily add support for new languages.
For example, internally Python support is 200 lines of code. But that's something you don't see. What you see are for example diffs in project events where we point out what exactly changed when a class changed it's grade. We also allow immediate feedback loop with our [playground](https://play.codebeat.co/).

**Comment by bf4** [comment]
Looks like reek merged it https://github.com/troessner/reek/pull/879#issuecomment-191285031 How are you deciding which gems to PR?


korzonek tomasz korzeniowski
korzonek tomasz korzeniowski 2

**Comment by korzonek** [comment]
We launched codebeat at the beginning of this year. codebeat is a team of three guys and we have been working on project for more than one year before release :) A few weeks ago we added support for open source and we all added a few open source projects in Swift, Go and Ruby that we like, know or looked cool... there was no sophisticated pattern behind :) I made PR to a few projects from the list.

We use reek on daily basis and reek is super cool project so this is a fantastic thing reek contributors accepted our badge. Thank you!

**Comment by NullVoxPopuli** [comment]
we use rubocop for most of our code quality checking -- how does your tool compare/differ with that? I see you have strict method-length requirements -- there are always exceptions to the rule, and I personally favor shorter methods, but it's kind of annoying when you just can't reduce a method any father, ya know?

**Comment by marcinwyszynski** [comment]
Hey, codebeat's CTO here. We actually use a combination or rubocop, reek and codebeat internally and each gives us a slightly different angle. Unlike rubocop codebeat does not focus on linting - by which I mean things like variable/class/constant names, line length etc.  Mapping what we do to the Ruby world where arguably there's a ton of good open-source tools already we're somewhere between rubocop, reek and flay. Over time we'll be adding more checks but most likely they'll be reek-style (code smells) rather than rubocop-style (style violation). Since our analysis is language-agnostic we can offer a consistent set of checks for all the languages we support. Which may not be important to a Ruby project but will probably be important to a lot of Ruby programmers who often use multiple technologies pretty much simultaneously.

Re: strict checks this is very much true and it's a mix of teething problems and conscious decisions. We'll eventually offer a way of silencing individual issues the same way rubocop or reek do it but it unlikely that we'll allow mix-and-match customisation of our core checks which are supposed to be based on community standards.

**Comment by NullVoxPopuli** [comment]
Well, I'd be game for adding the badge to our readme. Though I think I want to organize the badges, cause we have quite a few now. haha.

I'll organize the badges in a seperate PR, though.

@bf4, thoughts on this badge?

**Comment by NullVoxPopuli** [comment]
@rails-api/ams

**Comment by remear** [comment]
Honestly, I haven't noticed much that sets codebeat apart from code climate in the context of this project. With that being said, I like to support new projects and hope codebeat hits a unique stride. I'm ok with this being merged.

**Comment by marcinwyszynski** [comment]
@remear Have you tried opening diffs in the [RecentChanges](https://codebeat.co/projects/github-com-rails-api-active_model_serializers/recent_changes) section? I think this sets us apart at least a bit in that it shows what exactly happened that changed the rating of a particular namespace.

**Comment by remear** [comment]
I have, and I do find it helpful. Code Climate does a much more broad comparison view using GitHub. This feature of codebeat is one of the reasons why I qualified by previous comment with *much*. I think items like this are the "advantages" which previous comments were asking to be listed out.

**Comment by remear** [comment]
@korzonek Would you, or anyone from codebeat, like to open another PR to note this in the CHANGELOG in the misc section.

**Comment by korzonek** [comment]
@remear I've just created [PR](https://github.com/rails-api/active_model_serializers/pull/1569)

**Pull request merged**
