### PR TITLE
Design docs file format changed from textfile to github md

### PR DESCRIPTION
**Pull request by domitian**
`design.textile` file in docs folder is now `design.md` with github flavoured markdown syntax. Also fixed some  typos and grammatical mistakes in that file.

### CODE REVIEW

**Comment by domitian** [comment]
Not able to add label to the pull request.

**Comment by bf4** [comment]
Thanks for this @domitian 

I'm not sure there's much value to changing it to `md`, since it's really just an archival doc, but since you did the work, I'll take a look at it.

Based on your comment in #1487 it looks like a useful change would be make it more clear this not the current design.  The current design is the architecture doc.

**Comment by domitian** [comment]
@bf4 got your point, I changed the name of the doc to `LEGACY-DESIGN.md` which should make it clear that it is not current design doc.
Added to the start of this doc that this is not current design in bold case and to have a look at Architecture doc.

**Comment by bf4** [comment]
Thinking about the file names .... Original_design and rename architecture to design? Initial_design?

**Comment by domitian** [comment]
yeah, for renaming architecture to design is good.
legacy_design if feel will give more meaning to the other doc than initial/original design, we could also think of `old_design`

**Comment by bf4** [comment]
initial_? legacy and old don't really convey that it was the original design doc. Maybe in architecture just link to [serializers.textile in Rails (before reverted)](https://github.com/rails/rails/blob/fcacc6986ab60f1fb2e423a73bf47c7abd7b191d/railties/guides/source/serializers.textile) or [README.textile in first 0.0.1 commit](https://github.com/rails-api/active_model_serializers/commit/d72b66d4c5355b0ff0a75a04895fcc4ea5b0c65e?short_path=8aa641a#diff-8aa641a619b8ebeca0116d41774daf45) Or the [DESIGN.textline form 0-8-stable](https://github.com/rails-api/active_model_serializers/blob/0-8-stable/DESIGN.textile)? which was the source of this?

**Comment by bf4** [comment]
while you're in here or in a new PR, we also need to change the yard docs links in the readme to http://www.rubydoc.info/github/rails-api/active_model_serializers/v0.10.0.rc4 since master doesn't appear to be updating.. and maybe also http://www.rubydoc.info/github/rails-api/active_model_serializers/0-9-stable and http://www.rubydoc.info/github/rails-api/active_model_serializers/0-8-stable

**Comment by domitian** [comment]
@bf4 created a new PR for the Yard docs links #1491

**Comment by domitian** [comment]
As per this [commit](https://github.com/rails-api/active_model_serializers/commit/7d678844ae6900fa6cd8d1615f338d905c6dd73a) from you in the past, the source is 0.8-stable.
My suggestion is create a design folder and keep design documents for each version.

**Comment by bf4** [comment]
Well, the doc was copied from there but it originated in rails before 0.0.1. The readme references the readme's of 0.8 and 0.9 which already serve the purpose of their design

B mobile phone

**Comment by domitian** [comment]
So should we just remove the file and add references in architecture doc about the past design?

**Comment by bf4** [comment]
That's what I'm thinking now

B mobile phone

**Comment by domitian** [comment]
So should we link it and remove the file then?

**Comment by domitian** [comment]
Can I remove the file and add link in architecture.md then?

**Comment by bf4** [comment]
> Can I remove the file and add link in architecture.md then?

@domitian Yeah, that sounds good.

**Comment by bf4** [comment]
@domitian Are you still interested in finishing this PR? https://github.com/rails-api/active_model_serializers/pull/1490#issuecomment-179321838

**Pull request closed without merging**
