### PR TITLE
Merge multiple nested associations

### PR DESCRIPTION
**Pull request by fractaloop**
See #1054

### CODE REVIEW

**Comment by fractaloop** [comment]
I don't know what's up with the CI server, but this works with flying colors for me.

**Comment by bf4** [comment]
Yeah, that's pretty weird that it didn't respect the local config files

**Comment by bf4** [comment]
Can you add a test for this and add yourself to the changelog? thanks

**Comment by Hirtenknogger** [comment]
This seems to be a problem with Appveyor. may try again? @bf4 @fractaloop

**Comment by remear** [comment]
@fractaloop Are you interested in wrapping up this PR? bf4 mentioned some things that need to be addressed.

**Comment by fractaloop** [comment]
Blergh, I'm sorry but I don't use Ruby professionally anymore and I'm pretty rusty. I don't think I can get the tests added. Apologies! :sweat:

**Pull request closed without merging**
