### PR TITLE
Revert #665

### PR DESCRIPTION
**Pull request by nateberkopec**
This reverts commit 90343cea4dcdd84abd1a86cf3175e26bd0b7ca81.

### CODE REVIEW

**Comment by kurko** [comment]
@nateberkopec does this work on your app?

**Comment by nateberkopec** [comment]
@kurko Our 4.2 app's test suite is all green. https://github.com/rails-api/active_model_serializers/issues/766 is definitely fixed by this.

**Comment by kurko** [comment]
@nateberkopec ok, go with branch in your app for now. Will talk to @steveklabnik to release 0.9.3 after this is merged.

**Comment by dontfidget** [comment]
Thanks for trying to take this approach.  I've been trying to track down one other behavior that I think changed with 0.9.2 but I can't seem to reproduce it in test and I just wanted to make sure no one has seen this.  It had been my belief that you could embed serializer definitions within other serializer definitions and it would favor the embedded one.  For example,

```
class UserInfoSerializer < ActiveModel::Serializer
  class UserSerializer < ActiveModel::Serializer
    attributes :nested

    def nested
      'NESTED!'
    end
  end

  has_one :user
end
```

If you did this, I believe that the nested UserSerializer would supercede a UserSerializer defined outside of the serializer.  However, I can't get exhibit behavior in tests again any version in 0.9.x.

Am I wrong in believing that this ever was the case or could this be related to the changes introduced to support automatic reloading of serializers in development?  Thanks.

**Comment by kurko** [comment]
Not sure, but I think this should be in a separate issue.

**Comment by dontfidget** [comment]
OK, I'll open a separate note.  I just mentioned it here because this pull request seems to be ultimately it getting back to the original behavior, and I thought this might have been a regression.

**Comment by indirect** [comment]
I've been using this in my app today with Rails 4.2; it's fixed our issues and hasn't had any problems across four developers on four machines. :shipit:

**Comment by recurrence** [comment]
:+1: in my environment.  Solves a considerable headache :)

**Comment by meskyanichi** [comment]
I wasn't seeing any errors. However, my issue was #641, where the serializers were silently ignored and ALL attributes on my models were always serialized, instead of only the ones specified in the serializers.

Using this PR I am no longer seeing this issue in Rails 4.2.0. :+1:

**Comment by indirect** [comment]
@kurko think we can get a release? :grinning:

**Comment by kurko** [comment]
Perhaps yes :)

@klabnik ping

**Comment by kurko** [comment]
Er.. @steveklabnik

**Comment by kurko** [comment]
Released https://rubygems.org/gems/active_model_serializers/versions/0.9.3.

**Pull request merged**
