### PR TITLE
Update upgrade_from_0_8_to_0_10.md

### PR DESCRIPTION
**Pull request by brendon**
#### Purpose
Clarify the change in the way relationships are walked in 0.10.

#### Changes
Added an explanation to the upgrade documentation.

#### Related GitHub issues
#1127 

#### Additional helpful information

Just proposing a change to the upgrade guide to highlight the change in the way relationships are walked. Let me know if any of the details are wrong.

### CODE REVIEW

**Comment by richmolj** [comment]
@brendon LGTM. Could you squash these commits?

**Comment by NullVoxPopuli** [comment]
@richmolj we can squash ourselves

**Comment by NullVoxPopuli** [comment]
github has a button for that. "Squash and merge"

**Comment by richmolj** [comment]
@NullVoxPopuli never realized that, thanks!

**Comment by brendon** [comment]
Thanks @richmolj :) @NullVoxPopuli, I never was able to get the global configuration for `include` to work, but ended up not needing it in my project in the end. Hopefully it was just a quirk for me.

**Comment by richmolj** [comment]
@brendon afaik the global configuration is only referenced within the jsonapi adapter.

**Comment by brendon** [comment]
Ah righty, that makes sense then :)

**Pull request merged**
