### PR TITLE
Reverting PR #909

### PR DESCRIPTION
**Pull request by joaomdmoura**
Reverting PR #909 but also and adding json api usage advise on readme

### CODE REVIEW

**Comment by steveklabnik** [comment]
:cry: :cry: :cry: :cry:

**Comment by joaomdmoura** [comment]
:sob: sorry @seveklabnik , but I know we will define it as default soon! :disappointed: 
In the mean while we should promote it on some JS frameworks! It will help us into build a a standard and push jsonapi forward.

**Comment by steveklabnik** [comment]
I think this works _against_ that goal :/

**Comment by spastorino** [comment]
As I told you guys, let's not try to accomplish everything in one move.
AMS with JSON API as default won't be accepted in Rails. AMS with json adapter by default and an easy way to switch to JSON API will be.

**Comment by spastorino** [comment]
I'm totally fine with both ways for me it's just a switch I have to change to use what I need.
The thing is right now JSON API is not accepted as default in Rails.
If AMS' default adapter is JSON API I'm perfectly fine but I can't merge Rails API unless I completely remove AMS as a dependency on Rails side and I think that's much worse.

**Comment by joaomdmoura** [comment]
It's indeed worse Steve. This is why I agree with Santiago on this. Being integrated into Rails might even help  us in the long run when promoting json app. 





João M. D. Moura

**Comment by joaomdmoura** [comment]
As I discussed on IRC with @spastorino, it seem that you @steveklabnik, also agreed on this for now, so I'm merging it.

**Pull request merged**
