### PR TITLE
Factor `with_adapter` + force cache clear before each test.

### PR DESCRIPTION
**Pull request by beauby**

### CODE REVIEW

**Comment by bf4** [comment]
You might also want to check `git grep load_adapter` `git grep Adapter.create` `git grep Adapter.new`

**Comment by beauby** [comment]
@bf4 sure, I'll update all the tests if we decide to move forward on this.

**Comment by NullVoxPopuli** [comment]
This looks fantastic!

**Comment by joaomdmoura** [comment]
Nice, but need to rebase :grin:

**Comment by beauby** [comment]
Rebased! :+1:

**Comment by joaomdmoura** [comment]
Sorry about it @beauby can you rebase it again please? last time, I promisse :grin:

**Comment by beauby** [comment]
Rebased :+1:

**Comment by joaomdmoura** [comment]
Tks! merged! :smile:

**Pull request merged**
