### PR TITLE
Add object equality test for model serializers

### PR DESCRIPTION
**Pull request by semenyukdmitriy**
#### Purpose
Make `SomeSerializer.new(some_object)` == `SomeSerializer.new(some_object)`

#### Changes
Add `ActiveModel::Serializer#==` that checks if `object` is the same.

### CODE REVIEW

**Comment by beauby** [comment]
Could you point to an example where this would be desired?

**Comment by semenyukdmitriy** [comment]
@beauby I needed it when I tested a certain code to make sure it returns correct set of serializers like this:

```ruby
proper_result = [MySerializer(johns_post), MySerializer(jacks_post)]
expect(Posts.recent.decorate).to eq(proper_result)
```

**Comment by beauby** [comment]
Wouldn't it be possible to have your code return an array of serializer classes instead?

**Comment by bf4** [comment]
The way to do this is to include Comparable and define <=>

In any case, you'd need to take options into account as well

However, there's not really a natural case for sorting a renderee

**Pull request closed without merging**
