### PR TITLE
fix link on Getting Started page

### PR DESCRIPTION
**Pull request by CorainChicago**

### CODE REVIEW

**Comment by beauby** [comment]
Hey @CorainChicago, thanks for catching this. Would you mind modifying your PR so that it still uses a relative path though? (`/docs/general/serializers.md` instead of `docs/general/serializers.md`, i.e. the leading slash was missing). I'll merge right after.

**Comment by CorainChicago** [comment]
Thanks for the feedback.  I modified the PR to continue using the relative path. :)

**Comment by bf4** [comment]
Hi @CorainChicago!  Wanna practice your rebasing and squash these two commits down to one?  I'm around on slack and can pair. There's some (hopefully) helpful git links in https://github.com/rails-api/active_model_serializers/blob/master/CONTRIBUTING.md#about-pull-requests-prs

**Comment by CorainChicago** [comment]
@bf4 I think I got it rebased and squashed right.  Thanks for the suggestion, it was a great exercise to try rebasing and squashing my commits. :+1:

**Comment by bf4** [comment]
@CorainChicago Yup, that's what it's all about :).  Congrats on the PR!

Appendix: I forgot to ask you to add `[ci skip]` to your commit message. It's not terribly important, but for doc changes like this, it prevents CI from running, which is nice to the environment, others, the CI, etc. I don't always remember myself, but 'the more you know' :)

**Pull request merged**
