### PR TITLE
Change ActiveModelSerializers.config.adapter

### PR DESCRIPTION
**Pull request by lvrbrtsn**
to ActiveModel::Serializer.config.adapter

Running master I could only get my code to work by making this change.

### CODE REVIEW

**Comment by bf4** [comment]
Thanks for this.  Which ref on master?  Any way we can reproduce this?  I'm guessing you've looked at the code and have seen that the documentation is intentional. Is this test, dev, prod?  Please add additional information as requested by https://github.com/rails-api/active_model_serializers/blob/master/CONTRIBUTING.md

**Comment by lvrbrtsn** [comment]
TBH, I have no idea. I am pretty new. I just did a fresh rails 5 install, scaffolded out some resources and made a JSON initializer. When the init had the documentations adapter example I got this error. 

undefined method `config' for ActiveModelSerializers:Module

I made rails serve and the json_api format come through by making the changes to the adapter I did in the pull request. This is what I put in my gemfile.

gem 'active_model_serializers', '~> 0.10.0.rc2'

I hope that helps clear some things up.

**Comment by beauby** [comment]
@lvrbrtsn You're getting this error because we moved `ActiveModel::Serializer.config` to `ActiveModelSerializers.config` post 0.10.0-rc3, so the doc is really only relevant to master at this stage. I know the situation is not ideal, but we'll cut rc4 really soon (which will bring it much close to the docs), and it should be the last RC before the actual release.

**Comment by lvrbrtsn** [comment]
@beauby That clears everything up! Cool. Love the work you are all doing. So on rc4 I would switch back to what the docs say?

**Comment by beauby** [comment]
@lvrbrtsn Yup, exactly.

**Comment by lvrbrtsn** [comment]
@beauby Awesome! Thank you have a great day!

**Comment by beauby** [comment]
You're welcome! I'm closing this for now, feel free to keep commenting if you need further information!

**Pull request closed without merging**
