### PR TITLE
Add notes on how you can help to contributing documentation

### PR DESCRIPTION
**Pull request by JoshSmith**
I wanted to clarify further how someone new to the project could help. This is my first stab at it.

### CODE REVIEW

**Comment by joaomdmoura** [comment]
:+1:

**Comment by JoshSmith** [comment]
@joaomdmoura no issues with this at all?

**Comment by joaomdmoura** [comment]
@JoshSmith It sounds great me. There some details that we can add, but it's complementary:

If you want, you can also mention that anyone should feel comfortable to create issues that aim to discuss ideas / problems or implementations.

There are some other specific hints like, squash commits when open a big PR, write tests and always rebase master

**Comment by JoshSmith** [comment]
All great ideas. Let me change my PR.

**Comment by JoshSmith** [comment]
@joaomdmoura Implemented your suggestions. If you have any more, let me know. Otherwise you can always feel free to open an issue about it.

**Pull request merged**
