### PR TITLE
Remove the mailing list from the README

### PR DESCRIPTION
**Pull request by JoshSmith**
We discussed this previously, but I think it's time for the mailing list to be removed from the README. Every day more discussion, issues, and pull requests happen here then ever before. The mailing list is not representative of this activity and only dilutes the purpose of the blossoming community we're finding here.

A related note: I think we should actively encourage folks to ask questions on StackOverflow with the AMS tag, and put some documentation in here about that. I can open a separate PR for this later, but it would require more than a few of us to actively monitor SO and help where we can. If we successfully do this, then I think we effectively cover all the use cases the mailing list originally may have had.

### CODE REVIEW

**Comment by joaomdmoura** [comment]
@JoshSmith Totally agree. :+1:  BTW sorry about the test that is failing, It's inconsistent, I'm trying to fix and merge it with the Fragment Cache implementation. :stuck_out_tongue_closed_eyes:

**Comment by JoshSmith** [comment]
@joaomdmoura no worries!

@kurko I know we discussed before, but just want your sign-off on this.

**Comment by kurko** [comment]
Yesss, let's do it.

**Comment by JoshSmith** [comment]
:+1:

**Pull request merged**
