### PR TITLE
Fixes virtual value not being used

### PR DESCRIPTION
**Pull request by GriffinHeart**
First PR here so let me know if I should change something,

Noticed that `virtual_value` was never being used and this PR fixes it

### CODE REVIEW

**Comment by joaomdmoura** [comment]
hey @GriffinHeart I appreciate what you did here :smile:, but Virtual value is used behind the scenes, on every association that doesn't have a serializer itself as you check [here](https://github.com/rails-api/active_model_serializers/blob/master/lib/active_model/serializer.rb#L214)

I'm not sure if ```virtual_value``` was created to be used as an option. Because, as you can see on the the ```serializer.rb``` (link above), it wouldn't work on associations that doesn't have a serializer (or arrays where one elements doesn't have a serializer)

Also, I'm can't see a use case, because you can only work with static values. But if you use the a method to override it instead, you have access to ```object``` and ```scope```.

I'll not close it right now because I may have not seem some use case here, did you had something in mind when you decided to work on it? :smile: 

Btw your virtual value representation doesn't match the JSON API format. Check the [resource linakge](http://jsonapi.org/format/#document-resource-object-linkage) and the [resource identifier object](http://jsonapi.org/format/#document-resource-identifier-objects)

> ... A "resource identifier object" **MUST** contain **type** and **id** members.

**Comment by bf4** [comment]
On the other hand @GriffinHeart has pointed out that `val` is passed in but not used

```diff
-          resource[:relationships][name] = { data: nil }
+          resource[:relationships][name] = { data: val }
```

**Comment by joaomdmoura** [comment]
Indeed. But ```val``` should be parsed to follow JSON API conventions, even without a serializer.

**Comment by bf4** [comment]
Fortunately, it appears the only place this code is used is here.

```plain
50	        def add_relationship(resource, name, serializer, val=nil)
…	
137         def add_resource_relationships(attrs, serializer, options = {})
138           if association.respond_to?(:each)
139             add_relationships(attrs, name, association)
140           else
141	            if opts[:virtual_value]
142	              add_relationship(attrs, name, nil, opts[:virtual_value])
143	            else
144	              add_relationship(attrs, name, association)
```

Which means this code is equivalent to the below diff, unless I'm missing something

```diff
+50	        def add_relationship(resource, name, serializer)
-50	        def add_relationship(resource, name, serializer, val=nil)
…	
137         def add_resource_relationships(attrs, serializer, options = {})
138           if association.respond_to?(:each)
139             add_relationships(attrs, name, association)
140           else
141	            if opts[:virtual_value]
+142	          add_relationship(attrs, name, nil)
-142	          add_relationship(attrs, name, nil, opts[:virtual_value])
143	            else
144	              add_relationship(attrs, name, association)
```

**Comment by GriffinHeart** [comment]
@joaomdmoura Sorry for a late reply.

My biggest issue is that if you add relationships that don't have a serialiser using the jsonapi adapter they will be rendered as `nil`. When the relationship doesn't have a serialiser it will be using the `virtual_value` to carry the relationship.

In either case I just want the option to be able to render something instead of a `nil`, which I'm not sure is compatible with jsonapi 1.0

**Comment by joaomdmoura** [comment]
@GriffinHeart you are right! Just tested it. Great catch!

So yeah, I'm willing to merge it. But I don't think it should be an option. But this might be done in another PR.

Another optmization would be formatting the object to fit with the JSON API conventions as I mentioned earlier, guaranteeing it would have the usual ```type``` and ```id```keys.

I'm merging this one because it's a great fix! But would be awesome to see both optimizations in further PRs :smile:

**Comment by GriffinHeart** [comment]
@joaomdmoura Agreed, `virtual_value` doesn't make as much sense being a public option since you can always overwrite `attributes` and `relationships`

I think the real use case is not `virtual_value` just the ability to define the relationship like
```
has_many :rewards

def rewards
  { ...somestub }
end
```

and have the adapter use that for serialisation.

**Pull request merged**
