### PR TITLE
Add output examples for the adapters

### LINKED ISSUE #1314: Add examples for each adapter in docs.
Add examples *of a sample JSON output* for each adapter in [adapters.md](https://github.com/rails-api/active_model_serializers/blob/master/docs/general/adapters.md).

### PR DESCRIPTION
**Pull request by duduribeiro**
This PR will add output examples for the adapters (Default, Json, JsonApi). 

If this is not correct, just tell me and I can change it =D

Thanks, :beers: 

Closes #1314

### CODE REVIEW

**Comment by duduribeiro** [comment]
Just one little question. The `adapters.md` page tells 
`render @posts, include: ['authors', 'comments']`
Is the correct `render json: @posts, include: ['authors', 'comments']`
thanks =)

**Comment by bf4** [comment]
@duduribeiro Awesome! :+1: 

I wonder if there's a way to make the examples easier to compare.

> Is the correct `render json: @posts`

Yes :)

**Comment by bf4** [comment]
I'd also love if you took a look at my documentation PR which moves around a whole bunch of things https://github.com/rails-api/active_model_serializers/pull/1371

**Comment by duduribeiro** [comment]
Nice @bf4  =D.. I will think if we can display in a better way. 

to fix `render json: @posts`, I do it on this PR or in another?

I will see your PR \o/

cheers. :beers:

**Comment by beauby** [comment]
@duduribeiro Thanks for your work! I believe when you generate your examples you forgot to define a serializer for the authors though (which leads to inconsistent format, especially in the JSON API case). Could you fix it?

**Comment by beauby** [comment]
Hey @duduribeiro, any news on this?

**Comment by duduribeiro** [comment]
Hey @beauby.. I'll check this \o

**Comment by remear** [comment]
Hey, @duduribeiro. Are you still interested in wrapping this one up?

**Pull request closed without merging**
