### PR TITLE
Add serializer to association block context

### PR DESCRIPTION
**Pull request by bf4**
Perhaps there some method on the serializer that I want to use in the association block.
I couldn't because it is being evaluated in the 'Reflection' object.

- [x] Add serializer to Reflection evaluation binding
- [x] Test that we can a serializer method from an association block
- [x] Document usage
- [x] Add changelog

### CODE REVIEW

**Comment by groyoh** [comment]
Just as a proposal `block_value = instance_exec(serializer, &block)` would also be possible I guess and would be less "hidden".

**Comment by bf4** [comment]
@groyoh oh yeah, I forgot you can do that

**Comment by bf4** [comment]
oh, but then someone would need to add a block param. 


```diff
-             has_many :roles do
+             has_many :roles do |serializer|
                meta count: object.posts.count
                serializer.cached_roles
              end
```

it's kind of nicer without that, right?

**Comment by bf4** [comment]
```diff
diff --git a/lib/active_model/serializer/reflection.rb b/lib/active_model/serializer/reflection.rb
index 5257a90..1c70527 100644
--- a/lib/active_model/serializer/reflection.rb
+++ b/lib/active_model/serializer/reflection.rb
@@ -59,11 +59,9 @@ module ActiveModel
       def value(serializer)
         @object = serializer.object
         @scope = serializer.scope
-        # Add '@serializer' to binding for use in association block as 'serializer'
-        @serializer = serializer
 
         if block
-          block_value = instance_eval(&block)
+          block_value = instance_exec(serializer, &block)
           if block_value == :nil
             serializer.read_attribute_for_serialization(name)
           else
@@ -119,7 +117,7 @@ module ActiveModel
 
       protected
 
-      attr_accessor :object, :scope, :serializer
+      attr_accessor :object, :scope
 
       private
 
diff --git a/test/adapter/json_api/relationships_test.rb b/test/adapter/json_api/relationships_test.rb
index bf47a4e..5fa0de8 100644
--- a/test/adapter/json_api/relationships_test.rb
+++ b/test/adapter/json_api/relationships_test.rb
@@ -38,7 +38,7 @@ module ActiveModel
               end
             end
 
-            has_many :roles do
+            has_many :roles do |serializer|
               meta count: object.posts.count
               serializer.cached_roles
             end
```

**Comment by groyoh** [comment]
Yeah, my point was that just using `instance_eval` "hides" the fact that we can use `serializer` (also `object` and `scope`). With `instance_exec` you know that you're using the parameter. And if you don't need to use serializer, you can simply not add any parameter to your block.

I'm fine with any solution. I just wanted to point it out ;)

**Comment by bf4** [comment]
@groyoh I like the idea. Added a commit

**Comment by groyoh** [comment]
Why is appveyor taking so long?

**Comment by bf4** [comment]
@groyoh done now

**Comment by bf4** [comment]
Resolves https://github.com/rails-api/active_model_serializers/pull/1976

**Pull request merged**
