### PR TITLE
Update serializers.md

### PR DESCRIPTION
**Pull request by khanhpham1990**
#### Purpose
Remove plus operator

### CODE REVIEW

**Comment by groyoh** [comment]
It looks like this was intended as the code snippet is a diff (ref https://github.com/khanhpham1990/active_model_serializers/commit/26b089c8813d5d3b20581bd20d775e4f5ae76210). @bf4 could you confirm that?

**Comment by khanhpham1990** [comment]
Yes, i think this is bug editor. @groyoh @bf4 could you confirm that ?

**Comment by remear** [comment]
It's intentional. It's meant to draw attention to those specific lines as the changes needed to achieve what's being described in those respective areas.

@khanhpham1990 I'm interested to know if this intent wasn't obvious to you when you read through the documentation, or if you expected to see the examples presented in another manner.

**Comment by bf4** [comment]
I used the diff fence so it should have been green

**Comment by beauby** [comment]
Closing this as the format was intended. Let's keep commenting here to discuss possibilities of improving the docs!

**Pull request closed without merging**
