### PR TITLE
ActiveModelSerializers::Adapter::Attributes#serializable_hash transforms

### PR DESCRIPTION
**Pull request by krzysiek1507**
`ActiveModelSerializers::Adapter::Attributes` should also tranforms keys

### CODE REVIEW

**Comment by bf4** [comment]
@krzysiek1507 It shouldn't transform keys, though. That's a JSON API thing.  However, there's nothing to stop you from adding this behavior to your `ApplicationSerializer` super class.

**Comment by bf4** [comment]
I'm going to close this since I'm understanding it as a feature request and not a bug

**Comment by bf4** [comment]
But please respond to clarify

**Comment by krzysiek1507** [comment]
Thanks @bf4. I thought it was a bug.
Should JSON adapter require root key?

**Comment by bf4** [comment]
@krzysiek1507 

> Should JSON adapter require root key?

It will always have one, if that's what you mean by require

**Comment by krzysiek1507** [comment]
@bf4 thanks!

**Pull request closed without merging**
